title: BLOGari 
description: Deep learning
theme: jekyll-theme-architect
repository: afrago/dl-upna-face-recognition
markdown: kramdown
baseurl: /dl-upna-face-recognition
author:
  name: Ander Frago Landa
  url: https://anderfrago.github.io

sass:
  style: compact # possible values: nested expanded compact compressed
  
      